# Generated by Django 3.0.8 on 2022-04-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=40)),
                ('p_age', models.FloatField(default=0, null=True)),
                ('p_sex', models.CharField(blank=True, max_length=20)),
                ('p_phone', models.CharField(blank=True, max_length=20)),
                ('p_test_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=40)),
                ('test_description', models.CharField(blank=True, max_length=40)),
                ('test_price', models.FloatField(default=0, null=True)),
                ('test_code', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=20, null=True)),
                ('transaction_note', models.TextField(blank=True, null=True)),
                ('payment_creator', models.EmailField(help_text='Should be email', max_length=254, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Patient')),
            ],
        ),
    ]
